/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:c323fdc2-3c92-4cc8-805c-a0633ebf8730",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_KzT8i7h4Q",
    "aws_user_pools_web_client_id": "6vltg2c6vikd8hlsshrk17qinq",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "PHONE_NUMBER"
    ],
    "aws_appsync_graphqlEndpoint": "https://427gtq2hd5acnp3dwelg76j3nq.appsync-api.ca-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "ca-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-wnevqxkk2fbdbajqi63beik5eu",
    "aws_cloud_logic_custom": [
        {
            "name": "apirestforbusdb",
            "endpoint": "https://krmxfuue56.execute-api.ca-central-1.amazonaws.com/dev",
            "region": "ca-central-1"
        }
    ],
    "aws_user_files_s3_bucket": "teststoragev2221803-dev",
    "aws_user_files_s3_bucket_region": "ca-central-1"
};


export default awsmobile;
